/* Generated By:JavaCC: Do not edit this line. PropertyListParserConstants.java */
package org.apache.commons.configuration.plist;

interface PropertyListParserConstants
{
    int EOF = 0;
    int ARRAY_BEGIN = 5;
    int ARRAY_END = 6;
    int ARRAY_SEPARATOR = 7;
    int DICT_BEGIN = 8;
    int DICT_END = 9;
    int DICT_SEPARATOR = 10;
    int EQUAL = 11;
    int DATA_START = 12;
    int DATA_END = 13;
    int QUOTE = 14;
    int LETTER = 15;
    int WHITE = 16;
    int HEXA = 17;
    int DATA = 18;
    int STRING = 19;
    int QUOTED_STRING = 20;
    int ESCAPED_QUOTE = 21;

    int DEFAULT = 0;

    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"(\"",
        "\")\"",
        "\",\"",
        "\"{\"",
        "\"}\"",
        "\";\"",
        "\"=\"",
        "\"<\"",
        "\">\"",
        "\"\\\"\"",
        "<LETTER>",
        "<WHITE>",
        "<HEXA>",
        "<DATA>",
        "<STRING>",
        "<QUOTED_STRING>",
        "\"\\\\\\\"\"",
    };

}
