/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */
package org.apache.commons.configuration2.json;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface JSONParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARRAY_BEGIN = 5;
  /** RegularExpression Id. */
  int ARRAY_END = 6;
  /** RegularExpression Id. */
  int LIST_SEPARATOR = 7;
  /** RegularExpression Id. */
  int OBJECT_BEGIN = 8;
  /** RegularExpression Id. */
  int OBJECT_END = 9;
  /** RegularExpression Id. */
  int SEPARATOR = 10;
  /** RegularExpression Id. */
  int QUOTE = 11;
  /** RegularExpression Id. */
  int LETTER = 12;
  /** RegularExpression Id. */
  int HEXA = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int INTEGER = 16;
  /** RegularExpression Id. */
  int REAL = 17;
  /** RegularExpression Id. */
  int TRUE = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int NULL = 20;
  /** RegularExpression Id. */
  int ESCAPED_QUOTE = 21;
  /** RegularExpression Id. */
  int ESCAPED_BACKSLASH = 22;
  /** RegularExpression Id. */
  int ESCAPED_SLASH = 23;
  /** RegularExpression Id. */
  int ESCAPED_BACKSPACE = 24;
  /** RegularExpression Id. */
  int ESCAPED_FORMFEED = 25;
  /** RegularExpression Id. */
  int ESCAPED_NEWLINE = 26;
  /** RegularExpression Id. */
  int ESCAPED_RETURN = 27;
  /** RegularExpression Id. */
  int ESCAPED_TAB = 28;
  /** RegularExpression Id. */
  int ESCAPED_UNICODE = 29;
  /** RegularExpression Id. */
  int ESCAPED_CHARACTER = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"\\\"\"",
    "<LETTER>",
    "<HEXA>",
    "<DIGIT>",
    "<STRING>",
    "<INTEGER>",
    "<REAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\\/\"",
    "\"\\\\b\"",
    "\"\\\\f\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "<ESCAPED_UNICODE>",
    "<ESCAPED_CHARACTER>",
  };

}
