/*
 * Copyright 2006 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.commons.configuration.event;

import java.io.File;
import java.io.IOException;
import java.net.URL;

import org.apache.commons.configuration.AbstractConfiguration;
import org.apache.commons.configuration.XMLConfiguration;

/**
 * Test class for events generated by XMLConfiguration.
 *
 * @version $Id$
 */
public class TestXMLConfigurationEvents extends
        AbstractTestFileConfigurationEvents
{
    static final File TEST_FILE = new File("conf/test.xml");

    protected URL getSourceURL() throws IOException
    {
        return TEST_FILE.toURL();
    }

    protected AbstractConfiguration createConfiguration()
    {
        return new XMLConfiguration();
    }
}
