/* Generated By:JavaCC: Do not edit this line. PropertyListParserConstants.java */
package org.apache.commons.configuration2.plist;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface PropertyListParserConstants
{
    int EOF = 0;
    int ARRAY_BEGIN = 5;
    int ARRAY_END = 6;
    int ARRAY_SEPARATOR = 7;
    int DICT_BEGIN = 8;
    int DICT_END = 9;
    int DICT_SEPARATOR = 10;
    int EQUAL = 11;
    int DATA_START = 12;
    int DATA_END = 13;
    int DATE_START = 14;
    int QUOTE = 15;
    int LETTER = 16;
    int WHITE = 17;
    int HEXA = 18;
    int DATA = 19;
    int DATE = 20;
    int STRING = 21;
    int QUOTED_STRING = 22;
    int ESCAPED_QUOTE = 23;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"(\"",
        "\")\"",
        "\",\"",
        "\"{\"",
        "\"}\"",
        "\";\"",
        "\"=\"",
        "\"<\"",
        "\">\"",
        "\"<*D\"",
        "\"\\\"\"",
        "<LETTER>",
        "<WHITE>",
        "<HEXA>",
        "<DATA>",
        "<DATE>",
        "<STRING>",
        "<QUOTED_STRING>",
        "\"\\\\\\\"\"",
    };

}
